use imdb;

/* The haunting of Helena */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (56c38a6b-2904-4d69-900b-403ee7b8eb46, f2d9ddec-3e43-4c29-9b48-da604c26eb08, '2014-02-01', 'The haunting of Helena');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (5b24aaa9-5749-49e9-8e33-bfd201e813f9, f2d9ddec-3e43-4c29-9b48-da604c26eb08, '2014-02-01', 'The haunting of Helena');
  
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (c0c2efd3-a805-4460-a9e4-2b1af6e2722b, f2d9ddec-3e43-4c29-9b48-da604c26eb08, '2014-02-01', 'The haunting of Helena');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (3c74dbcf-bff8-4922-a992-7ebc4eb54cb9, f2d9ddec-3e43-4c29-9b48-da604c26eb08, '2014-02-01', 'The haunting of Helena');
  

/* Closed circuit */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (77f92efc-f48d-4f01-80a2-25c12ec9915c, 08cbbce4-4341-4f26-888f-5a842af819f8, '2014-02-01', 'Closed circuit');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (272505d8-0e33-4837-90a9-cd79ad79396f, 08cbbce4-4341-4f26-888f-5a842af819f8, '2014-02-01', 'Closed circuit');
  
/* Enders Game */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (4239a7c1-4427-4321-b588-de50590994b2, 0a1ec3aa-9333-458f-b859-4cf149c71bc8, '2014-02-01', 'Enders Game');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (c51be3f9-4963-4675-91f2-f314d0287e17, 0a1ec3aa-9333-458f-b859-4cf149c71bc8, '2014-02-01', 'Enders Game');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (eee25de1-2939-4ca7-9598-eb30b3077b97, 0a1ec3aa-9333-458f-b859-4cf149c71bc8, '2014-02-01', 'Enders Game');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (d596f571-51ff-4282-8594-180a2bfdf2b4, 0a1ec3aa-9333-458f-b859-4cf149c71bc8, '2014-02-01', 'Enders Game');

/* Runner runner */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (cb5ac670-02ff-4d5e-8702-037a004fd1cf, 1cf766e7-e054-46ac-97e0-0b987c0134a4, '2014-02-01', 'Runner runner');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (e3838466-ed81-41f7-851c-f93c7430e9c9, 1cf766e7-e054-46ac-97e0-0b987c0134a4, '2014-02-01', 'Runner runner');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (da049843-e062-49d9-b196-d6e83600796e, 1cf766e7-e054-46ac-97e0-0b987c0134a4, '2014-02-01', 'Runner runner');


/* Gravity */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (a88fafb2-51d5-459b-bd92-7c23eed7d168, 3ce7ac33-a452-49c0-9832-2944fef51c35, '2014-02-01', 'Graviry');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (e96ff2f1-193a-4c48-83f3-f91c9824aa3a, 3ce7ac33-a452-49c0-9832-2944fef51c35, '2014-02-01', 'Graviry');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (62236f97-5a74-4915-9584-c8a6ad4e11ec, 3ce7ac33-a452-49c0-9832-2944fef51c35, '2014-02-01', 'Graviry');

/* Gambit, el plan perfecto */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (cbd384ef-4712-4a9c-9147-5da8c4500330, 438c7131-7550-4188-ad8d-47ac9a4c280e, '2014-02-01', 'Gambit, el plan perfecto');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (9a3041a0-edf0-49bf-91b0-80e85fc150b5, 438c7131-7550-4188-ad8d-47ac9a4c280e, '2014-02-01', 'Gambit, el plan perfecto');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (f14745a5-2d03-4fcd-8551-844610ea8381, 438c7131-7550-4188-ad8d-47ac9a4c280e, '2014-02-01', 'Gambit, el plan perfecto');

/* Redemption */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (5d14fd5d-fd5c-45ff-b701-b4fcf259da42, 66c3facf-4ba7-477e-95dd-731ff5b08c55, '2014-02-01', 'Redemption');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (11ffffbe-94b6-40b5-a205-0484bf8d6a2e, 66c3facf-4ba7-477e-95dd-731ff5b08c55, '2014-02-01', 'Redemption');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (68e99fab-7beb-42ea-b9ae-9b1803e5c9a3, 66c3facf-4ba7-477e-95dd-731ff5b08c55, '2014-02-01', 'Redemption');

/* The frozen ground */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (fb6c681d-968e-42d4-8e98-4af33fc39af9, 7011f15d-37a4-4df6-8cba-9c7095a08e49, '2014-02-01', 'The frozen ground');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (805a8a59-2e34-438c-8949-8a515a673809, 7011f15d-37a4-4df6-8cba-9c7095a08e49, '2014-02-01', 'The frozen ground');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (77fee274-53ff-4d0e-9bde-6e9ceedb71d5, 7011f15d-37a4-4df6-8cba-9c7095a08e49, '2014-02-01', 'The frozen ground');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (ec3eedc8-ea44-457f-897f-18db051d724a, 7011f15d-37a4-4df6-8cba-9c7095a08e49, '2014-02-01', 'The frozen ground');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (89221f82-0e74-4f4a-9c75-e2890fc18038, 7011f15d-37a4-4df6-8cba-9c7095a08e49, '2014-02-01', 'The frozen ground');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (b338bcd3-a39b-4ec7-9829-36ec1f5e1098, 7011f15d-37a4-4df6-8cba-9c7095a08e49, '2014-02-01', 'The frozen ground');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (3c5ff2ad-b3e6-4db4-8a55-789610b95844, 7011f15d-37a4-4df6-8cba-9c7095a08e49, '2014-02-01', 'The frozen ground');

/* Jackass: Bad Grandpa */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (e6ae7934-fd71-445c-ab80-866ffb2b4554, 72c42922-6620-4b85-a2fc-e0f13d088a87, '2014-02-01', 'Jackass: Bad Grandpa');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (5d64a0f4-3c62-4bf6-8488-e401e9d356f5, 72c42922-6620-4b85-a2fc-e0f13d088a87, '2014-02-01', 'Jackass: Bad Grandpa');

/* As i lay dying */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (b8e0b24c-667d-43e5-b37b-20121eb21ee6, 83511038-15d0-4cc4-90bc-94b6ed0f2b8d, '2014-02-01', 'As i lay dying');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (ce06cf4b-c72a-4d0e-90a9-581b939f5d07, 83511038-15d0-4cc4-90bc-94b6ed0f2b8d, '2014-02-01', 'As i lay dying');


/* The Butler */
insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (199e7218-d457-4fbd-828d-22716527c7ff, f4d4449e-d0df-4fb3-9d7e-ffc824279835, '2014-02-01', 'The Butler');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (4fbc55ac-7490-4191-b1d1-f70a3fb5d91a, f4d4449e-d0df-4fb3-9d7e-ffc824279835, '2014-02-01', 'The Butler');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (14a1918f-b5e7-440b-8129-9f0d0700357b, f4d4449e-d0df-4fb3-9d7e-ffc824279835, '2014-02-01', 'The Butler');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (199e0a18-984d-4033-b673-9988e9b52b3c, f4d4449e-d0df-4fb3-9d7e-ffc824279835, '2014-02-01', 'The Butler');

insert into "actores_peliculas" (actor_id,	pelicula_id, fecha_estreno,	titulo)
  values (805a8a59-2e34-438c-8949-8a515a673809, f4d4449e-d0df-4fb3-9d7e-ffc824279835, '2014-02-01', 'The Butler');

  